"""The chips / mult flames (Balatro's 'flame' shader on the HUD boxes) as a looping pixel-art animation.

    python3 tools/make_flames.py          -> SPRITESHEETS/flames.png (+ manifest entry)

Balatro lights flames above the chips and mult boxes once the hand's score reaches the blind
(button_callbacks.lua flame_handler): colour_1 = the box colour (BLUE / RED), colour_2 = the 'lick'
((colour/2 + YELLOW/2) + 0.1)^2 (mult; for chips a light blue reads truer than the formula's green). Generated, not a supplied asset: FRAMES frames of rising, flickering tongues,
24 x 32 font-style pixels upscaled x4. Row 0 = chips (blue), row 1 = mult (red); the base of the flame is the bottom
edge of each tile.
"""
import json
import math
import os

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
W, H, FRAMES, UP = 24, 32, 8, 4
BLUE, RED, YELLOW = (0, 157 / 255, 1.0), (254 / 255, 95 / 255, 85 / 255), (1.0, 1.0, 0.0)


def lick(c):
    return tuple(min(1.0, max(0.1, ((c[i] * 0.5 + YELLOW[i] * 0.5) + 0.1) ** 2)) for i in range(3))


def heat(x, y, f):
    """0..1 flame heat at pixel (x, y) (y = 0 at the base) in frame f; loops every FRAMES frames"""
    u = (x + 0.5) / W - 0.5                      # -0.5 .. 0.5 across
    v = (y + 0.5) / H                            # 0 base .. 1 top
    t = 2 * math.pi * f / FRAMES
    sway = 0.06 * math.sin(7 * v - t) + 0.03 * math.sin(13 * v - 2 * t + 1.3)
    width = 0.46 * (1 - v) ** 0.85 + 0.02
    edge = 1 - abs(u - sway * v) / max(width, 1e-6)
    tongues = 0.5 + 0.5 * math.sin(18 * u + 9 * v - 2 * t) * math.sin(11 * u - 14 * v + t + 0.7)
    lift = 0.12 * math.sin(t + 2.1 * u) + 0.06 * math.sin(2 * t + 5 * u)      # tongues reach up and fall back
    h = edge * (1.15 + lift - v) + 0.6 * (tongues - 0.5) * v
    return max(0.0, min(1.0, h))


def main():
    white = (1.0, 1.0, 1.0)
    rows = [(BLUE, tuple(0.4 * a + 0.6 * b for a, b in zip(BLUE, white))), (RED, lick(RED))]   # chips core: light blue
    sheet = Image.new("RGBA", (W * FRAMES, H * len(rows)), (0, 0, 0, 0))
    px = sheet.load()
    for r, (c1, c2) in enumerate(rows):
        for f in range(FRAMES):
            for y in range(H):
                for x in range(W):
                    h = heat(x, y, f)
                    if h < 0.12:
                        continue
                    if h > 0.62:
                        col, a = c2, 1.0                     # hot core: the lick colour
                    elif h > 0.3:
                        col, a = c1, 1.0                     # body: the box colour
                    else:
                        col, a = c1, 0.55                    # thin edge
                    px[f * W + x, (r + 1) * H - 1 - y] = tuple(round(255 * v) for v in col) + (round(255 * a),)
    sheet = sheet.resize((sheet.width * UP, sheet.height * UP), Image.NEAREST)
    file = "SPRITESHEETS/flames.png"
    sheet.save(os.path.join(ROOT, file), optimize=True)
    man_path = os.path.join(ROOT, "SPRITESHEETS", "manifest.json")
    man = json.load(open(man_path))
    entry = {"file": file, "url": "https://vasiniks.github.io/BAlrotro/" + file, "image_px": list(sheet.size),
             "tile_px": [W * UP, H * UP], "layout": "grid", "columns": FRAMES, "rows": len(rows), "count": FRAMES * len(rows),
             "order": "row 0 chips (blue), row 1 mult (red); column = animation frame", "source": "generated by tools/make_flames.py"}
    man["sheets"] = [s for s in man["sheets"] if s["file"] != file] + [entry]
    with open(man_path, "w") as fh:
        json.dump(man, fh, indent=1, ensure_ascii=False)
        fh.write("\n")
    print(file, sheet.size)


if __name__ == "__main__":
    main()
